{'include/*', [debug_info, 
           {i, "include/"},
           {outdir, "ebin"}]}.

{'src/*', [debug_info, 
           {i, "include/"},
           {outdir, "ebin"}]}.

{'src/env/*', [debug_info,
              {i, "include/"},
              {outdir, "ebin"}]}.